version: "3.9"
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.10
    ports: ["8080:8080", "50051:50051"]
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "none"   # you push external vectors
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:

